language: python

python:
    - 3.6

install:
    - pip install .
    - pip install -r requirements.txt
    - pip install pylint
    - pip install coveralls

script:
    - pytest -n 12 --cov=nn_dataflow

after_success:
    - pylint --disable=R0801 nn_dataflow/
    - coveralls

